# Generated by Django 2.2.7 on 2019-11-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='name',
            field=models.CharField(default='noname', max_length=100),
        ),
    ]
