# Generated by Django 2.2.7 on 2019-11-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_reg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='email',
            field=models.EmailField(default='noemail', max_length=254),
        ),
        migrations.AddField(
            model_name='reg',
            name='password',
            field=models.CharField(default='1234', max_length=25),
        ),
        migrations.AddField(
            model_name='reg',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
