# Generated by Django 2.2.7 on 2019-11-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191119_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='phone',
            field=models.CharField(default='00000000000', max_length=12),
        ),
    ]
