# Generated by Django 2.2.7 on 2019-11-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191119_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='name',
            new_name='username',
        ),
    ]
